workflows:
  android-boxer-timer:
    name: Boxer Timer APK Build
    max_build_duration: 20
    instance_type: mac_mini_m1
    environment:
      android_満:
        ndk: 25.2.9519653
        sdk: 33
    triggering:
      events:
        - push
    scripts:
      - name: Set up local.properties
        script: | 
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
      - name: Build Android APK
        script: | 
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - dein-email@beispiel.de # <-- Hier deine E-Mail-Adresse eintragen!
        notify:
          success: true
          failure: true
